const endpoints = {
    LOGIN_CANDIDATE: '/candidate/login',
    LOGIN_COMPANY: '/company/login',
    SIGNUP_CANDIDATE: '/candidate',
    SIGNUP_COMPANY: '/company',
    GET_MY_CANDIDATE: '/candidate/my',
    GET_MY_ACADEMIC_GRADUATION: '/graduation/my',
    CREATE_ACADEMIC: '/graduation',
    UPDATE_ACADEMIC: '/graduation/',
    DELETE_ACADEMIC: '/graduation/',
    GET_MY_EXPERIENCE: '/experience/my',
    CREATE_EXPERIENCE: '/experience',
    UPDATE_EXPERIENCE: '/experience/',
    DELETE_EXPERIENCE: '/experience/',
    GET_STUDY_AREAS: '/study_area',
    GET_TYPE_LOCALITY: '/type_locality',
    GET_JOB_TYPE: '/job_type',
    GET_SECTOR: '/sector',
    GET_SKILL: '/skill?',
    SEARCH_VACANCIE: '/vacancie?',
    GET_MY_VACANCIE: '/vacancie/my',
    CLOSE_VACANCIE: '/vacancie/close/',
    CREATE_VACANCIE: '/vacancie',
    UPDATE_VACANCIE: '/vacancie/',
    GET_COMPANY_VACANCIE: '/vacancie/company/',
    DELETE_VACANCIE: '/vacancie/',
    CREATE_CANDIDACY: '/candidacy',
    GET_MY_CANDIDACY: '/candidacy/my',
    DELETE_CANDIDACY: '/candidacy/',
    APPROVE_CANDIDACY: '/candidacy/approve/',
    DISAPPROVE_CANDIDACY: '/candidacy/disapprove/'
}

export default endpoints;
